# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy source code and build the project
COPY . .
RUN npm run build

# Start the server in stdio mode
CMD [ "npm", "start" ]
